### ISSUE TITLE
Documentation Improvement

### ISSUE THREAD

**Issue by Ian-Stewart-Binks** [Courseography/courseography#149]
The code is lacking a lot of necessary documentation. Rather than 'doing it by year', as I find most people do, I've decided to make an issue for this to give it the proper time that it deserves.

- [x] JavaScript Documentation

**Comment by Ian-Stewart-Binks** [comment]
@david-yz-liu It looks like the majority of what this issue was trying to achieve has been achieved. There are other issues for some missed JSDocs.

Permission to close?

**Comment by david-yz-liu** [comment]
@Ian-Stewart-Binks Yep! Good work. :)
