### ISSUE TITLE
Graph: CSC438's description is incorrect

### ISSUE THREAD

**Issue by Ian-Stewart-Binks** [Courseography/courseography#162]
At least, I think it is:
>[if gte mso 9]> Normal 0 false false false EN-CA X-NONE X-NONE

**Comment by Ian-Stewart-Binks** [comment]
@david-yz-liu Did you fix this in your first `web-request` branch commit?

**Comment by david-yz-liu** [comment]
No, web-request currently doesn't touch the JSON files.
