### ISSUE TITLE
Search box should have search symbol

### ISSUE THREAD

**Issue by Ian-Stewart-Binks** [Courseography/courseography#167]
I propose that the search box have an icon, such as:

https://www.google.ca/search?q=search+symbol+png&oq=search+symbol+png&aqs=chrome..69i57.2653j0j7&sourceid=chrome&es_sm=0&ie=UTF-8

**Comment by david-yz-liu** [comment]
@pkukulak You're on this one.

**Comment by pkukulak** [comment]
Sure! What's the search box in question? I'm drawing a blank in my mind.

**Comment by david-yz-liu** [comment]
In the Grid, where you type in courses.
