### ISSUE TITLE
SVG Parser

### ISSUE THREAD

**Issue by Ian-Stewart-Binks** [Courseography/courseography#188]

**Comment by Ian-Stewart-Binks** [comment]
@david-yz-liu Should we close this issue and make new issues for the new features of the parser?

**Comment by david-yz-liu** [comment]
@Ian-Stewart-Binks I think closing this is a good idea. However, I don't think we should open any more issues unless they are bugs for this issue.

**Comment by Ian-Stewart-Binks** [comment]
@david-yz-liu Sounds good. There is some tweaking that can be done for the parser, for instance in some places we hard code the transformation. Though, I am uncertain if I should add these as issues because we will be converting the parser to Haskell at some point.
