### ISSUE TITLE
Transfer JSON to SQL

### ISSUE THREAD

**Issue by Ian-Stewart-Binks** [Courseography/courseography#190]
Transfer JSON to SQL, specifically postgres.

**Comment by david-yz-liu** [comment]
Basically done now, due to @shaftoes

**Comment by Ian-Stewart-Binks** [comment]
Can we expunge the (majority) of the web_parsing code?

Do we want to make an issue for converting to postgres in the future?

**Comment by david-yz-liu** [comment]
Yeah, let's get rid of that directory entirely.

Let's hold off on switching databases for now... I think we need to do some more research.

**Comment by Ian-Stewart-Binks** [comment]
Should we save enrol_parser?

**Comment by david-yz-liu** [comment]
No, we can rewrite in Haskell this summer
