### ISSUE TITLE
Upgrade Parsing

### ISSUE THREAD

**Issue by Ian-Stewart-Binks** [Courseography/courseography#192]
New 200 series courses have been added for CS. These courses should be added to both the graph and the grid.

CSC309 is still displaying a bug where the T5101 8pm tutorial displays on Fridays (I believe between 10am-11am or such).

**Comment by Ian-Stewart-Binks** [comment]
@david-yz-liu It looks like this has been completed, correct?

**Comment by david-yz-liu** [comment]
Yes, thanks @Ian-Stewart-Binks!
