### ISSUE TITLE
Change Courseography Description

### ISSUE THREAD

**Issue by Ian-Stewart-Binks** [Courseography/courseography#208]
I think that it's time to create a new description for Courseography. The current one, *"Courseography is a tool created by David Liu and Ian Stewart-Binks to guide students through their undergraduate careers. "*, doesn't feel like it represents the project fully and doesn't acknowledge future contributors. 

The README should also be updated sometime in the future to better reflect the work done on Courseography.

@david-yz-liu Thoughts?

**Comment by Ian-Stewart-Binks** [comment]
@david-yz-liu It looks like this issue may have been forgotten. I've updated the `README.md` file with the about page, but I do not have permission to change the Courseography GitHub description.

**Comment by david-yz-liu** [comment]
Thanks, Ian! This did indeed drop off my radar. I'll take a look at your PR soon.

**Comment by Ian-Stewart-Binks** [comment]
@david-yz-liu Should we still change the description?

**Comment by david-yz-liu** [comment]
The repo description is automatically taken from the README file in the master repo, which is why it hasn't yet changed.

When I merge happstack into master, it'll automatically update.
