### ISSUE TITLE
Parser: Course Descriptions Are Missing Spaces

### ISSUE THREAD

**Issue by Ian-Stewart-Binks** [Courseography/courseography#232]
Some of the parsed course descriptions are missing spaces in between course strings such as `fromCSC148H1toCSC108H1` in `res/courses/CSC148H1.txt`.

**Comment by Ian-Stewart-Binks** [comment]
@shaftoes This is no longer an issue, correct?

**Comment by shaftoes** [comment]
Correct. I haven't come across any courses where this is the case so I think we're good.
