### ISSUE TITLE
Graph: New Graph Missing Prereq

### ISSUE THREAD

**Issue by Ian-Stewart-Binks** [Courseography/courseography#233]
The new graph is missing the prerequisite 324 -> 488.

**Comment by david-yz-liu** [comment]
It is missing a few more than this. It appears that when multiple courses appeared in a hybrid, only the one course is appearing.

**Comment by Ian-Stewart-Binks** [comment]
This is going to take a bit of work, I forgot that SVG text wrapping/newlines in text elements is a tricky task. It shouldn't be that bad, though.
