### ISSUE TITLE
Update CSC Prerequisites

### ISSUE THREAD

**Issue by arkon** [Courseography/courseography#234]
CSC309 no longer requires CSC343 (or at least it didn't this past semester).

**Comment by david-yz-liu** [comment]
Okay, I checked with the Undergraduate office. Two changes should be made to the graph:

- [ ] Remove 343 from 309
- [ ] Remove Sta2 from 411

@christinem @pkukulak @jmatholia @shaftoes Working on one or both of these changes should be an easy fix for any of you.

**Comment by christinem** [comment]
@david-yz-liu I can make these changes.
