### ISSUE TITLE
MAT138 JSON question

### ISSUE THREAD

**Issue by Ian-Stewart-Binks** [Courseography/courseography#238]
Why are Mat138H1's tutorial sections formed as `"tutorials": [["T5101", [[0, 17]], "M5", 53, 22, 0], ["T5201", [[2, 19]], "W7", 53, 22, 0]]`? What do the final three digits represent?

**Comment by Ian-Stewart-Binks** [comment]
Note that this is the only course that produces tutorials as arrays of length > 3.

**Comment by Ian-Stewart-Binks** [comment]
CSC324 is has tutorial sections as `[[[78,47,65],[[0,11]],"M11"],[[78,47,65],[[0,11]],"M11"],[[78,47,65],[[3,18]],"R6"]]`.

**Comment by david-yz-liu** [comment]
I'm not able to reproduce either of these issues. However, it does appear that the times for MAT138 fail to be parsed. You can verify that and then make an issue for it.

**Comment by Ian-Stewart-Binks** [comment]
Where are you seeing that times for MAT138 fail to be parsed?

**Comment by david-yz-liu** [comment]
If you run web_parsing/main.py only getting the FAS timetable (and not calendar), no file for MAT138 is created.
