### ISSUE TITLE
Graph: CSS Error 

### ISSUE THREAD

**Issue by david-yz-liu** [Courseography/courseography#241]
When you load the graph, an error message "Unexpected value strokewidth parsing markerUnits attribute." is displayed in the console.

**Comment by Ian-Stewart-Binks** [comment]
There is a chance that the bug may exist in the file `courseography/utilities/svg_parsing/svg_parser.py` around line 58. I am not certain of this, however.

**Comment by Ian-Stewart-Binks** [comment]
PR merged. Is this still good to close?

In any case, it was mentioned that there are still potential jQuery errors happening. I'll make an issue for that.

**Comment by david-yz-liu** [comment]
Thanks, @Ian-Stewart-Binks
