### ISSUE TITLE
Select courses when in "spotlight" mode?

### ISSUE THREAD

**Issue by david-yz-liu** [Courseography/courseography#251]
From a user: "I noticed that when you select a focus from the focuses tab you are unable to select courses. This makes it difficult for people who don't remember what courses are required for a particular focus to plan out their course selection. What they would have to do is click on the focus then unclick it to actually choose courses and then click it again once they have forgotten some of the courses necessary. I think this could be improved by somehow allowing the user to click on the highlighted courses when a focus is selected."

**Comment by Ian-Stewart-Binks** [comment]
Note that this has been brought up before in #72, and was noted by Jasmin Lantos in her review of Courseography : *"I think this could be improved by somehow allowing the user to click on the highlighted courses when a focus is selected. Thus, "reducing the need for users to rethink and remember" which is a phrase I stole from the reuse principle over [here](http://en.wikipedia.org/wiki/Principles_of_user_interface_design)"*.

This is a popular suggestion.

**Comment by david-yz-liu** [comment]
Ah, I did think we had talked about this one before. Well, this one's a bit long term now anyway, since it's not clear what we're doing with focuses any more.

**Comment by christinem** [comment]
Bringing this to the forefront since this issue has been mentioned again by some people, as the focuses work the same way as they did in the old graph - it was suggested that people be able to click on courses while a focus is highlighted. @david-yz-liu what do you think? I think I could easily do this.

**Comment by david-yz-liu** [comment]
@christinem Okay, you have my blessing to go ahead. The unlit courses should appear grayed out though.

**Comment by david-yz-liu** [comment]
Closed in #805.
