### ISSUE TITLE
Can't select/de-select courses after clicking "Info"

### ISSUE THREAD

**Issue by christinem** [Courseography/courseography#252]
A friend recently pointed this out to me:

On the live courseography graph, if you press the "Info" button beside any course to bring up the pop-up, and then click outside of the box to exit from the Info pop-up and go back to the graph, you can no longer select/de-select any courses. You need to refresh the window or click the "Reset" in order to be able to select/deselect courses again.

**Comment by Ian-Stewart-Binks** [comment]
Perfect! This is a bug that David and I had noticed before but unfortunately it seems to have been forgotten about. Thanks for adding, Christine!

**Comment by david-yz-liu** [comment]
Yes! If you wanted to take a look at this one, that would be great too. It might be an easy fix, but if it isn't, I wouldn't worry about fixing it for next week.

**Comment by christinem** [comment]
I'll definitely give it a stab!

**Comment by Ian-Stewart-Binks** [comment]
In case you're stuck on where to start, `js/graph/modal.js` is a file that likely contains something that plays a role in the bug. `js/graph/mouse_events.js` may be helpful as well.

**Comment by david-yz-liu** [comment]
@christinem has told me that this doesn't happen any more on the happstack branch. In that case, I'm okay closing this one.
