### ISSUE TITLE
Text opacity in happstack

### ISSUE THREAD

**Issue by Ian-Stewart-Binks** [Courseography/courseography#258]
Unlike in the current version of Courseography, the opacity of the nodes in the graph of the happstack branch do not change when a course's state changes (e.g. `takeable -> inactive`).

Should we change this back to the behaviour on the current (master) version of Courseography?

**Comment by christinem** [comment]
Did you guys still want this changed back to how it was on master? If so, I can take this on.

**Comment by david-yz-liu** [comment]
Sure, go for it!
