### ISSUE TITLE
jQuery Errors

### ISSUE THREAD

**Issue by Ian-Stewart-Binks** [Courseography/courseography#261]
It was mentioned in the meeting on January 12th that members are experiencing errors in the console. There errors are along the lines of `jQuery... GET`, if I am not mistaken.

**Comment by Ian-Stewart-Binks** [comment]
@pkukulak I think you mentioned this. Do you know if/how we can recreate these errors?

**Comment by pkukulak** [comment]
![screen shot 2015-01-14 at 4 05 26 pm](https://cloud.githubusercontent.com/assets/6440833/5747597/33e07f7e-9c07-11e4-9bcc-38a43326419b.png)

It seems to pop up in the console every time I load the application. I'll look into it.

**Comment by david-yz-liu** [comment]
The error looks like the file isn't being found, which is really odd. I just tried the URL and it seems to work.

**Comment by christinem** [comment]
I used to get this error quite a bit a week or so ago as well, but now it doesn't seem to appear anymore. It's really odd. It could be an error that's machine-independent.

**Comment by Ian-Stewart-Binks** [comment]
@pkukulak Do you get the error every time you load the page?

**Comment by pkukulak** [comment]
I believe so, yes. When I have a few moments, I will refresh frantically and see if it persists.

**Comment by pkukulak** [comment]
Pops up every time.

![screen shot 2015-01-16 at 6 55 47 pm](https://cloud.githubusercontent.com/assets/6440833/5786345/6485fac2-9db1-11e4-9d2f-15159e065c16.png)

**Comment by Ian-Stewart-Binks** [comment]
Strange. I just got it when visiting `http://.../graph` seconds after the server went up. Refreshed, and it went away.

**Comment by david-yz-liu** [comment]
Okay, sounds like an async call is failing. @pkukulak please bring in your machine on Monday and I'll take a look.

**Comment by arkon** [comment]
By the way, using a [Google-hosted copy of jQuery](https://developers.google.com/speed/libraries/devguide#jquery) might be a good idea (for reliability and speed).

**Comment by david-yz-liu** [comment]
@arkon's absolutely right. Let's get one of @pkukulak @shaftoes @jmatholia on that.

**Comment by Ian-Stewart-Binks** [comment]
@shaftoes please take this issue. If you have any questions, feel free to ask me. This shouldn't take too much work.

**Comment by shaftoes** [comment]
Sure thing -- how do I assign myself to an issue?

**Comment by david-yz-liu** [comment]
@shaftoes Only I can assign people to issues, so if you ever want to take one, just let me know!

**Comment by david-yz-liu** [comment]
@pkukulak Can you check if you still have this issue?

**Comment by pkukulak** [comment]
@david-yz-liu  Sorry for the delay. The error no longer pops up when I load the page; we're in the clear!

**Comment by david-yz-liu** [comment]
@pkukulak Okay, sounds good. I guess this was just a matter of the javascript file loading slowly...
