### ISSUE TITLE
Run cssGen.hs when the server starts

### ISSUE THREAD

**Issue by david-yz-liu** [Courseography/courseography#263]
I think it would be a good idea to automatically compile the css files when the server starts (at least in development mode). Shouldn't be too hard to do.

**Comment by Ian-Stewart-Binks** [comment]
Sounds good. I can take this on.

**Comment by Ian-Stewart-Binks** [comment]
I will also create `SVGGen.hs`. So really, I will just run `python3 ../setupy.py` and change the relative paths.

**Comment by david-yz-liu** [comment]
No, don't do that. Changes in SVGGen.hs need to be recompiled with server.hs, and so needs to happen before the server starts.

However, you should remove the cssGen line from setup.py.

**Comment by Ian-Stewart-Binks** [comment]
Hmm. You're right.

I'm not certain if this is the best idea, but perhaps we could have a script that generated SVGGen.hs and then ran the server. It also saves us the hassle of writing `-idatabase`  every time.

When working on the parsers, I wasted a lot of time by going
`python3 setup.py`
`cd hs`
`runhaskell -idatabase server.hs`
`cd ..`

**Comment by david-yz-liu** [comment]
@Ian-Stewart-Binks I don't think it's worth spending any more time on; SVGGen.hs should be pretty stable now.
