### ISSUE TITLE
cssGen can't generate style files

### ISSUE THREAD

**Issue by Ian-Stewart-Binks** [Courseography/courseography#264]
Haskell's `writeFile` function appears to need the directories in the path of the file that is being written to to exist. Git unfortunately doesn't add in empty directories.

E.g. `cssGen.hs: style/graph/graph_styles.css: openFile: does not exist (No such file or directory)`
(This is after adding in `style` and `style/common`.)
What should we do?

**Comment by david-yz-liu** [comment]
Hmmm, I think I used the wrong git command; didn't mean to actually delete all the files, just untrack them.

Oh well, this can be fixed with this function: http://hackage.haskell.org/package/directory-1.2.1.0/docs/System-Directory.html#v:createDirectoryIfMissing. Can you do this?

**Comment by Ian-Stewart-Binks** [comment]
Tricky business. I can't get it to work yet.

`createDirectoryIfMissing` seems to also create directories for files (it creates `common.css` as a directory, for instance).

I have made an attempt on my branch `issue-264`, but have so far been unsuccessful.

I am uncertain whether `writeFile` creates files if they do not exist, but I do know that `openFile` will.

The current error message I get right now is `cssGen.hs: style/common/common.css: openFile: does not exist (No such file or directory)`.

@david-yz-liu Do you have any suggestions that may push this forward?

**Comment by david-yz-liu** [comment]
It seems like you're on the right track, although I don't think it should be necessary to change render style file. See the commit I tagged you in; does that work for you?

**Comment by Ian-Stewart-Binks** [comment]
Can't seem to find the commit. So many branches. So many repositories. So little GitHub notification. Where is it?

**Comment by david-yz-liu** [comment]
Ah, well I just merged a PR for the change. You can find it near the top of the closed PR list.

**Comment by Ian-Stewart-Binks** [comment]
Works for me! I am going to close this issue.

**Comment by Ian-Stewart-Binks** [comment]
(Thanks!)
