### ISSUE TITLE
MAT221/223/240 are not listed on the calendar

### ISSUE THREAD

**Issue by munrocape** [Courseography/courseography#265]
As a result, you cannot "complete" the math requirement for the Specialist. 

I could not find this in the issue backlog. 

If not, would it just be an addition to planner.html for the edges and node? 

Is this being worked on? If not, I would be interested in sorting that out.

**Comment by david-yz-liu** [comment]
Hey @munrocape, those courses are listed under the "Lin1" node, although this is probably not the best name. If you select this node, the checkbox should be checked.

If you're interested in contributing in a way related to the graph-drawing, I'd absolutely love it if you made a graph for MAT or ECE (this would involve making one from scratch, which might be fun). This would be a huge step forward for us!

**Comment by munrocape** [comment]
@david-yz-liu Ah this is linear algebra. I took this to mean Linguistics given the focus. Thanks for the clarification :blush: 

When you say a new graph, do you mean a fork of this that would map the MAT or ECE programs?

**Comment by david-yz-liu** [comment]
No, a fork is not necessary; only a new SVG file is required. Switch to the happstack branch and look at res/graphs/graph_regions.svg

**Comment by munrocape** [comment]
Sorry, fork was the incorrect terminology. I meant a map that was a similar implementation as the CSC program. I would imagine a user could then select from a list of programs which one to display.

**Comment by david-yz-liu** [comment]
Yeah, that's right. I have another student working on such an interface right now, but we do not actually have a second graph... yet.

**Comment by munrocape** [comment]
Cool! Good to hear.

I'll begin to poke around how things work.

**Comment by munrocape** [comment]
Cool! Good to hear.

So a javascript file defines the pre-reqs and relationships, and the svg defines the grid? What else is required to wire it up? 

Also, I noticed mentioning sending you a mail for a spreadsheet. Is this required?
