### ISSUE TITLE
GET Request 404 Error for styles.css

### ISSUE THREAD

**Issue by christinem** [Courseography/courseography#268]
It seems, with the recent changes made to the generation of css files, there is now a GET Request 404 error for static/style/graph/styles.css - it seems that CssGen.hs is not generating the styles.css file when running setup.py.

**Comment by Ian-Stewart-Binks** [comment]
`styles.css` is probably a fossil from master.

There should be an easy solution. Christine, do you want to tackle this or should I? I can supply help if you want to take it.

**Comment by christinem** [comment]
I was thinking that might be it. 
Yeah I can tackle this one.

**Comment by david-yz-liu** [comment]
@christinem Are the other files being generated? (Check the timestamp?)

**Comment by christinem** [comment]
@david-yz-liu actually, no, the others aren't being generated when running setup.py. I deleted my style folder and running setup.py does not regenerate it with its files. Has the method for generating them changed?

**Comment by david-yz-liu** [comment]
Oh, yeah sorry. (@Ian-Stewart-Binks can you please update the wiki?) You should just need to run server.hs now (but if that doesn't work, please let me know).

**Comment by Ian-Stewart-Binks** [comment]
This issue is not yet resolved. The server is still trying to get `styles.css`.

**Comment by Ian-Stewart-Binks** [comment]
And yes.

**Comment by christinem** [comment]
@david-yz-liu server.hs is having an import issue with JsonParser and Tables because they're not in the same directory.

**Comment by Ian-Stewart-Binks** [comment]
Are you running `server.hs` with the same flag listed in the install guide?

**Comment by christinem** [comment]
Ah, for some odd reason it wasn't generating the folder at first but it seems to be fine now.
But yes the console error still exists so I will try and take that on.

**Comment by Ian-Stewart-Binks** [comment]
In case you get stuck, a good place to snoop around is the `hs` directory. A file that can help you track down where the bug is generated is `MasterTemplate.hs`. Though, this is likely not the file that contains the bug.

**Comment by Ian-Stewart-Binks** [comment]
Could this issue have anything to do with #261?

**Comment by christinem** [comment]
Thanks for the guidance @Ian-Stewart-Binks! And I'm not entirely sure, I feel like they might be unrelated. The styles error is a new one for me, but the jquery error from #261 was happening for about a week atleast. Oddly enough THAT error (the jquery one) is not in my console right now.
