### ISSUE TITLE
Courseography Nav Bar Layout Issue

### ISSUE THREAD

**Issue by Ian-Stewart-Binks** [Courseography/courseography#278]
On a screen with resolution = 1024 x 768, the Nav Bar links are too close to the Courseography title.
![Ex:](https://cloud.githubusercontent.com/assets/6301000/5796591/c56569d6-9f78-11e4-9744-9c27146540ed.png)

**Comment by Ian-Stewart-Binks** [comment]
So this no longer happens. The nav bar now displays very nicely on my display with res. 1024 x 768, even when using the browser's (Chrome's and Firefox's) zoom function.

**Comment by david-yz-liu** [comment]
Sweet.
