### ISSUE TITLE
Generate Grid's 'appendTableData' quotation mark use

### ISSUE THREAD

**Issue by Ian-Stewart-Binks** [Courseography/courseography#289]
generate_grid.js' `appendTableData` function uses `"` when it should be using `'`.

**Comment by foreverwander** [comment]
I fixed it in my timetable branch, sorry I don't know how to edit my happstack branch locally, but I guess i'll submit a pull request anyway?

**Comment by foreverwander** [comment]
fixed!

**Comment by Ian-Stewart-Binks** [comment]
Ah! Thank you! 

Changes that change the functionality and changes that change the style should usually be submitted as different pull requests. This can be accomplished by having two separate branches that both branch out from the `happstack` branch.

**Comment by foreverwander** [comment]
oh icic. so the commit would have to onto a new branch... oh well, i was changing stuff with the file anyways~ it just got all put into the same pull request...
