### ISSUE TITLE
Grid - course names

### ISSUE THREAD

**Issue by david-yz-liu** [Courseography/courseography#290]
Inside the table, we currently display selected sections with their full codes, "CSC108H1". I think we should do two things

1. Only display the dept and number, but omit the last two letters: "CSC108".
2. Specify either "(L)", "(T)", or "(P)" to distinguish lectures, tutorials, and practicals: "CSC108 (L)".

**Comment by Ian-Stewart-Binks** [comment]
Interesting. I think that this is a good idea, and it shouldn't take too long to implement either one.

**Comment by christinem** [comment]
I like the idea too, but (maybe this is long term) once UTM courses come in, those last two letters might be important (since UTM courses have alot of the same course codes but an "H5" at the end)

**Comment by david-yz-liu** [comment]
I don't know that I care to distinguish between campuses on the timetable, though of course it should be in the course selection pane. It's something that people should have in their heads regardless of what appears in the timetable.

**Comment by christinem** [comment]
@david-yz-liu ah, I misread a little bit, I realize you meant just on the timetable grid. I was thinking of the course selection pane as well. I agree then that it's not needed on the timetable itself.

**Comment by christinem** [comment]
@david-yz-liu I think I'd like to take this issue on.
