### ISSUE TITLE
Grid - Remove colours for section types

### ISSUE THREAD

**Issue by david-yz-liu** [Courseography/courseography#291]
Related to #290, we should not use colours to distinguish between different kinds of sections (lecture/tutoral/practical).

To complete this issue, remove all styling which distinguishes the types of sections in the grid, both in the table and in the left sidebar.

**Comment by Ian-Stewart-Binks** [comment]
Should we keep the styling that distinguishes between courses in which all required types of section have been taken (e.g. CSC209 lecture and tutorial)? I believe that the code refers to these states as 'satisfied' and 'unsatisfied'.

**Comment by david-yz-liu** [comment]
@Ian-Stewart-Binks I think a warning icon (the yellow triangle with an exclamation mark) is better for that.

**Comment by Ian-Stewart-Binks** [comment]
@david-yz-liu Yeah, that actually sounds a lot better than having different colours. Good idea.
