### ISSUE TITLE
Requesting a course from the server - query parameters

### ISSUE THREAD

**Issue by Ian-Stewart-Binks** [Courseography/courseography#292]
In server.hs, we retrieve part of the URL and make queries based on that. It looks like using query parameters is much more conventional and more extensible. I think that it would be good if we switched from parsing the path to using query parameters.

Here is the section of server.hs that I am referring to.
`dir course $ path (\s -> liftIO $ queryCourse s)`.

**Comment by david-yz-liu** [comment]
Yeah, I meant to say this a while ago, but thanks for pointing this out! A good idea.

**Comment by Ian-Stewart-Binks** [comment]
This isn't a hard fix and it should be a very good learning experience for both Haskell and Happstack. If anyone wants to take this on, I can walk them through any difficulties that they may encounter.

Two files that would definitely need to be changed are `server.hs` and another file in the `js` directory.

**Comment by david-yz-liu** [comment]
@shaftoes I'm assigning you this one. Please consult with @Ian-Stewart-Binks when you get a chance. Also, there's a good example on the wiki for this.

**Comment by shaftoes** [comment]
alright!
