### ISSUE TITLE
FCE Count

### ISSUE THREAD

**Issue by Ian-Stewart-Binks** [Courseography/courseography#302]
It appears that the FCE count does not exist in the happstack Graph. Is this something that we want to bring back?

Whenever planning my courses, I always found it to be very useful.

**Comment by david-yz-liu** [comment]
I like it! Perhaps it could go on the top right, in the nav bar.

I still want to see a sidebar or something for the graph as well; this will be essential when switching between graphs, or bringing back focuses.

**Comment by Ian-Stewart-Binks** [comment]
Ah good point.

I noticed yesterday that many of the PRs had something in common: they all added a new button to the navigation bar. This is something that we should think about, we may run out of real estate up there.

Should we add the side bar as an issue? I'm fine if we leave the layout until after the projects have made more progress. @jmatholia has a cool sidebar for the graph drawing, perhaps we could make them similar.

**Comment by david-yz-liu** [comment]
I agree that the Nav bar may end up being cluttered; we may need a "More..." link, like on some other websites.

I don't think we should make an issue for the side bar just yet, since it's not at all clear to me what the final designs of every page will be, and that's a larger conversation to have.

**Comment by christinem** [comment]
I like the idea of a sidebar later on. Actually, having it for the switching of graphs would be a very convenient idea.

**Comment by Ian-Stewart-Binks** [comment]
The FCE count appears to be used with the Check My Post LI, however it isn't always consistent.

Is this where the FCE count will live?

**Comment by christinem** [comment]
@Ian-Stewart-Binks can you explain what you mean by "isn't always consistent"? Maybe I can do something to fix that.

**Comment by christinem** [comment]
Plus the FCE count I have set up right now doesn't take into account exactly how many courses are selected - only the amount of courses selected that satisfy each POSt. For example, if you have taken more 300+ level courses than needed for a POSt, it does not count them. So I don't know if you want a more general FCE count that counts exactly how many courses one has selected regardless of POSt.

**Comment by david-yz-liu** [comment]
@christinem Yes, a "more general FCE count" would be a good thing to add in a side bar.

**Comment by christinem** [comment]
@david-yz-liu Sounds good. Shouldn't be too hard to do since it just means adjusting some of the code I have now. Sidebar is next on my list too - both for graph switching and perhaps focuses - so I'll see how I can incorporate it.

**Comment by christinem** [comment]
@Ian-Stewart-Binks I see what you mean by inconsistent now. Sometimes it shows up and sometimes it doesn't. Thanks, I'll take a look at that too.
