### ISSUE TITLE
InkScape SVG Importing

### ISSUE THREAD

**Issue by Ian-Stewart-Binks** [Courseography/courseography#308]
I'm having trouble properly importing graph_regions.svg into InkScape.

The imported SVG appears like this:
![inkscape_problem](https://cloud.githubusercontent.com/assets/6301000/5943160/9d3b249a-a6ea-11e4-8545-86a9b1f5f931.png)

This also happens when converting from SVG to PNG via the command line.

@christinem Is there a specific way that the SVG needs to be imported into InkScape? Am I doing something incorrectly?

**Comment by david-yz-liu** [comment]
@Ian-Stewart-Binks That's odd, I just tried it and it looks fine to me.

**Comment by Ian-Stewart-Binks** [comment]
@david-yz-liu Hmm. I've tried upgrading inkscape, but am still on version Inkscape 0.48.4 r9939 (Jan 22 2014). What version are you on?

**Comment by christinem** [comment]
@Ian-Stewart-Binks I just opened it in Inkscape, I didn't import it. Is that perhaps what you are doing?

**Comment by christinem** [comment]
@Ian-Stewart-Binks Actually, importing it seems to be fine for me as well. 

My version of is Inkscape 0.48.5 r10040

**Comment by Ian-Stewart-Binks** [comment]
@christinem I've tried importing and just opening. It looks like 0.48 is available on Linux as well, I'll try this out when I can.

**Comment by Ian-Stewart-Binks** [comment]
Ah, the graph was also created with `inkscape:version="0.48.5 r10040"`. This is most likely the fix.

**Comment by christinem** [comment]
@Ian-Stewart-Binks hah, well that is interesting. I am the last one who worked on it. I guess as long as you use a newer or equivalent version of inkscape, because when I imported the one from before, it worked fine.

**Comment by Ian-Stewart-Binks** [comment]
Nope, the version wasn't the problem... It's also a little concerning that apt-get installs Inkscape as 81mb and then removes it as 67mb...

@christinem , are you still dual booting Ubuntu 14.04?

**Comment by christinem** [comment]
@Ian-Stewart-Binks yeah I am. Would you like me to try installing Inkscape on there and see how it looks?

**Comment by Ian-Stewart-Binks** [comment]
Yeah, that would be fantastic. Thanks!

**Comment by Ian-Stewart-Binks** [comment]
You can use the command `sudo apt-get install inkscape`. If you can't get 0.48.5, I can help you install it (the default seems to be 0.48.4 with apt-get).

**Comment by christinem** [comment]
Yeah you're right, the default is 0.48.4, but I managed to find the repository to download 0.48.5. Oddly enough, you're right: I have the same issue now on Ubuntu:

![graph](https://cloud.githubusercontent.com/assets/5077973/5950798/a41d7b9a-a72c-11e4-92ab-894ba0ee045c.png)

**Comment by Ian-Stewart-Binks** [comment]
Interesting. I'll see what I can do about notifying the Inkscape developers, should they not already know of this exclusive Ubuntu feature.

For now, it's probably best that I just try to move on with life.

**Comment by Ian-Stewart-Binks** [comment]
[First time submitting a bug!](https://bugs.launchpad.net/inkscape/+bug/1415734)

I hope I did it right!

**Comment by Ian-Stewart-Binks** [comment]
I'll take this on.
