### ISSUE TITLE
The "x" in the left sidebar of the grid does not register as clickable

### ISSUE THREAD

**Issue by christinem** [Courseography/courseography#319]
It's small, but I think it'd be nice, whenever you hover over either the "x" or the "i" images on the left sidebar of the grid (where you can either remove a course from the list or see the info modal), for it to register as clickable, as when you hover over an "a" element. Its just a bit disorienting when you hover over it right now - you believe the "x" has no function until you actually click it.

**Comment by Ian-Stewart-Binks** [comment]
I completely agree.

In fact, I don't like that red X.

**Comment by christinem** [comment]
I can actually do this. 

As for whether we want to keep the X or not, that'd be interesting conversation to have.

**Comment by david-yz-liu** [comment]
Sounds good. Adding the mouse pointer should be fine for now. @Ian-Stewart-Binks, you are free to suggest an alternate icon, or something else entirely.

**Comment by david-yz-liu** [comment]
@Ian-Stewart-Binks While I'm closing this issue, if you find another icon to use, great.

**Comment by Ian-Stewart-Binks** [comment]
I will keep my eyes peeled.
