### ISSUE TITLE
Selection on Graph doesn't remain when switching tabs

### ISSUE THREAD

**Issue by christinem** [Courseography/courseography#334]
I'm curious to know if this is just me or not - whenever I select some courses from the graph, switch a tab, and then come back to the graph, the selections seem to disappear. However the cookies remain unchanged - a course I had clicked before switching tabs still shows as active in its cookie when I switch back to the graph. This happens in both my branch and the happstack branch.

![screenshot 219](https://cloud.githubusercontent.com/assets/5077973/6101014/2659ef10-afea-11e4-9e65-229175a540a1.png)

**Comment by Ian-Stewart-Binks** [comment]
Good note. Not just you. Most likely an issue with how we are resurrecting the graph based on the cookies. I can't imagine any reason why the new graph would introduce this bug...  Perhaps I am forgetting something... The functionality is there, but something's not clicking...

**Comment by Ian-Stewart-Binks** [comment]
The issue should be in the function `initializeGraphSettings` in `js/graph/utilities/util.js`.

When we made the new graph, we needed to do some cleaning. It looks like not everything in that function may be... functional.

**Comment by Ian-Stewart-Binks** [comment]
Ah. Got the solution. It appears some refactoring of old code didn't quite make it into the aforementioned function... I redirect attention to `node.js`, line 11.

There appears to have been some funky merging done, as well. It appears that there are two `node`

**Comment by david-yz-liu** [comment]
@christinem I think you should take this one - you're getting very familiar with cookies, anyway.

**Comment by christinem** [comment]
Sounds great! Can do.
