### ISSUE TITLE
Refactor node colours

### ISSUE THREAD

**Issue by david-yz-liu** [Courseography/courseography#339]
@pgries raised the issue of duplicated code in specifying colours of different node groups today. I think this would be a good issue for @jmatholia since you've been working with this part of the CSS anyway. It's a good Haskell learning experience, too.

**Comment by Ian-Stewart-Binks** [comment]
Note that node colours are no longer specified in the CSS, and are now specified in the graph generator.

**Comment by jmatholia** [comment]
It seems the node colours associated with the "Draw" nodes are also no longer in GraphCss.hs. Should I hard code it into the svg or put it back in GraphCss.hs?

Also just to make sure does that mean the refactoring is not an issue anymore? Were there any other places in the css generation code we needed to refactor?

**Comment by david-yz-liu** [comment]
This is no longer an issue for the manually-created graphs, as the node colours are specified by hand. For the "Draw" tab, well, that's up in the air.
