### ISSUE TITLE
Generate the prerequisite dependencies on the server

### ISSUE THREAD

**Issue by david-yz-liu** [Courseography/courseography#342]
Right now, the Javascript function buildGraph is called every time the page is loaded, computing intersections to get dependencies.

We should be able to do this server-side, as part of the SVG parsing process. The goal would be to generate a javascript file that creates the relevant data structures directly.

This is a larger issue, but fits nicely with all the work that @Ian-Stewart-Binks is doing. Progress on this issue can be made on the svg-schema branch.

**Comment by Ian-Stewart-Binks** [comment]
Aye aye.

**Comment by Ian-Stewart-Binks** [comment]
This issue has been completed and is up for review.
