### ISSUE TITLE
Re-introduce Reset Button

### ISSUE THREAD

**Issue by christinem** [Courseography/courseography#351]
I think we should re-introduce the reset button on the graph (to clear all the selected courses), as is in the live version.

**Comment by Ian-Stewart-Binks** [comment]
I agree. I think it's about time.

Should we keep the button on the graph, or move it over to some sort of... tool bar?

**Comment by christinem** [comment]
@Ian-Stewart-Binks I'm not quite sure yet. Once I start working on the graph-switching, another toolbar or sidebar might be introduced, so perhaps it could go there? Though I don't see anything wrong with keeping it on the graph if that's not too difficult.
