### ISSUE TITLE
Check my POSt constraint bugs

### ISSUE THREAD

**Issue by christinem** [Courseography/courseography#366]
- [x] In Major, 4th Year Category does not turn green when completed
- [x] In Major, Inquiry constraints should overlap with other categories, but it does not
- [x] Course Credit Count is broken
- [x] Autofilled Text Boxes should be uneditable

**Comment by Ian-Stewart-Binks** [comment]
@christinem Is this issue fixed?

**Comment by christinem** [comment]
@Ian-Stewart-Binks yes it is. Odd that it didn't close itself with the merge of my branch. But yeah it's fixed.
