### ISSUE TITLE
Structs.js is missing JSDocs

### ISSUE THREAD

**Issue by Ian-Stewart-Binks** [Courseography/courseography#383]
`js/graph/utilities/structs.js` is missing JSDocs. This should be fixed.

**Comment by Ian-Stewart-Binks** [comment]
It looks like a merge was done incorrectly. `structs.js` was covered in my `documentation` branch last fall... Proof: https://github.com/Courseography/courseography/commit/2ae9e20d22521d5809950d287dcfffd14b5ebda6

Scroll down to `structs.js`.

**Comment by christinem** [comment]
Seems as though the JSDocs got removed in this: acfda93
I can take this on and add the JSDocs back.

**Comment by Ian-Stewart-Binks** [comment]
You're absolutely right @christinem. Thanks for taking this on!
