### ISSUE TITLE
Draw: When bottom is best edge.

### ISSUE THREAD

**Issue by jmatholia** [Courseography/courseography#385]
At the moment when an elbow is directly below the destination node, the top edge is chosen even though the bottom edge is obviously the right choice.
![image](https://cloud.githubusercontent.com/assets/9491656/6383643/c31b7218-bd20-11e4-9d5b-65347c3fd61f.png)

**Comment by Ian-Stewart-Binks** [comment]
What do you suspect is the cause of this behaviour?

**Comment by jmatholia** [comment]
When I talked about how the best edge is chosen I glossed over the details. With direct paths (no elbows) the combination of edges that ensures the shortest path is chosen. But with paths that have elbows I did some logical calculations with the coordinate of the elbow and the top left corner of the node. There is probably a flaw in the logic somewhere. It should be fine if I also chose paths between elbows and nodes that create the shortest path.

**Comment by Ian-Stewart-Binks** [comment]
Hmm. I can take a look at the code that performs these actions, a second set of eyes may be helpful. Can you provide a snippet that you suspect is causing this behaviour?

I think that d3 (or some library built off of d3) has something along the lines of 'edge ports', in which an edge can only be connected to one of these ports (I believe that the ports are n,s,w,e,ne,nw,se,sw). Does our code do something similar?

**Comment by jmatholia** [comment]
The related code is lines 335 to 358 in draw.js. However I warn you there are some weird criteria for choosing a specific edge. Choosing the closest edge to the elbow would be a lot simpler (i.e. using the same method as with 2 nodes lines 310 to 329). There might be some edge cases to consider.

**Comment by Ian-Stewart-Binks** [comment]
@jmatholia This is fixed, correct?

**Comment by jmatholia** [comment]
Yes, this is fixed.
