### ISSUE TITLE
Draw: Firefox compatibility.

### ISSUE THREAD

**Issue by jmatholia** [Courseography/courseography#386]
The whole draw tab is not functional with firefox (cannot create nodes and thus paths), most likely because at the moment rect id's don't have begin with alpha characters.

**Comment by Ian-Stewart-Binks** [comment]
@jmatholia Has this been fixed?

**Comment by jmatholia** [comment]
I have added the workaround but it is not fixed. I am still looking for an alternative to offsetLeft and offsetTop in firefox, or why exactly they are not defined.

**Comment by david-yz-liu** [comment]
@jmatholia This must be a solved problem (i.e., finding the coordinates of a mouse clicked); doing some searching online might produce some code you can use.

**Comment by Ian-Stewart-Binks** [comment]
@jmatholia Has this been fixed?

**Comment by jmatholia** [comment]
No, not yet.

**Comment by Ian-Stewart-Binks** [comment]
@jmatholia So this has this been fixed? Don't edit comments in the future if you want people to see what you have to say, the alert wasn't sent out, I just happened to check this issue.
