### ISSUE TITLE
Installation Guide Update

### ISSUE THREAD

**Issue by Ian-Stewart-Binks** [Courseography/courseography#388]
The installation guide needs to be updated to include:
- [x] New graph generation procedure
- [x] New Haskell dependencies
- [x] New command to run server
- [x] New directory structure

**Comment by Ian-Stewart-Binks** [comment]
I've been having some bad OS issues lately, and had to reinstall a lot of stuff. The past few times that I've installed Courseography from scratch, I've also had to install `zlib1g-dev` for the zlib package, one of Happstacks dependencies. 

Should we make a list of common installation errors?

**Comment by christinem** [comment]
I think this might be handy. I have had quite a few issues with installation/updating stuff when dealing with courseography. Just now, with the most recent database and svg changes, I had to reinstall courseography from scratch and it took about two hours or so to get all the dependencies working (I had to do a little hack to build one of them).

**Comment by Ian-Stewart-Binks** [comment]
@christinem I'm currently having issues with the graphics library. I've installed `alex`, but `gtk2hs-buildtools` can't seem to find it, which is necessary for `glib`.

What did you do to get over this?

**Comment by christinem** [comment]
@Ian-Stewart-Binks I actually am having the same issue trying to install '''glib'''. I'll look around to see if I can find a way to get around it.

**Comment by christinem** [comment]
I can take this on. @Ian-Stewart-Binks is it just the parser.hs and the new way to build the database and run the server? Plus looks like setup.py is gone too and not needed for the installation. 
I think that roundabout way to build the database still exists too, doesn't it?

**Comment by Ian-Stewart-Binks** [comment]
Thanks Christine! @david-yz-liu made a pull request to fix the database issue. I haven't tried it out yet.

Yes, it should just be those things. Dependencies too (HaXml... I can't remember the others... Data.List.Split I believe...). If you see anything that you know shouldn't be in there, feel free to take it out.

**Comment by christinem** [comment]
I did a pull and I still seem to have the same database issue unfortunately. I still have to run it from hs and then move the sqlite3 file to the database folder - it can't be run from the database folder directly. But other than that, yeah absolutely!

**Comment by christinem** [comment]
@david-yz-liu  @Ian-Stewart-Binks Seems as though I can't run parser.hs properly anymore with the directory changes. I made an issue for both the database and the parser. I think I might hold off on updating the Installation Wiki until those two get solved.

**Comment by christinem** [comment]
I've updated the installation guide. Please let me know if I've missed anything/made a mistake somewhere. :)

**Comment by Ian-Stewart-Binks** [comment]
Thanks! 

For inline code you can just use the `single tick`. Triple ticks are for multi-line code, as far as I know. There are also check boxes for this issue up in the first comment.

**Comment by Ian-Stewart-Binks** [comment]
`hs/database` should be `hs/Database`.

Also, I don't know what we should do at this point, but the files generated by `utilities/web_parsing` are not used by the database.

**Comment by christinem** [comment]
@Ian-Stewart-Binks thanks! Oddly it seems like it doesn't allow me to check boxes myself in the first comment- I think only the creator of the comment can. And thanks for the corrections!
And is that so? Hmm, should I take out the part with `utilities/web_parsing` then for now?

**Comment by Ian-Stewart-Binks** [comment]
I'm going to say leave it in until we don't need it any more. I still need the instructions to continue the facebook branch.

**Comment by christinem** [comment]
@Ian-Stewart-Binks sounds good then! I think this issue is about solved then, unless someone thinks anything should be added.

**Comment by Ian-Stewart-Binks** [comment]
Sounds good. Thanks Christine!
