### ISSUE TITLE
Can't install `diagrams`

### ISSUE THREAD

**Issue by Ian-Stewart-Binks** [Courseography/courseography#391]
@christinem and I are having difficulty installing the `diagrams` package through cabal.

I can't install `glib`, because I can't install `gtk2hs-buildtools-0.13.0.3`, because I can't install `alex`. Or rather, I can install `alex`, but cabal can't find it after the installation.

**Comment by christinem** [comment]
The only way I could install diagrams was to use this command:

```cabal install Diagrams --constrain "arithmoi -llvm"```

Although the issue I had when trying to install it was different than yours (the dependency ```type-level-0.2.4``` would not build), so I don't know if this will necessarily solve it.

**Comment by Ian-Stewart-Binks** [comment]
Interesting. I've been able to install diagrams by itself, but needed to install `LLVM` to install `arithmoi-0.4.1.1`. However, when running `cabal install persistent diagrams`, the previous error is raised. However, `cabal install happstack diagrams` works fine.

**Comment by christinem** [comment]
I was having an issue downloading ```LLVM``` because of the ```type-level``` dependency. What this above command does is it installs diagrams without the support of llvm, so that whole domino-effect of errors is avaded. Although I don't know if that will be a problem in the future.

**Comment by Ian-Stewart-Binks** [comment]
I was able to install `LLVM`, but the `arithmoi-0.4.1.1` package was telling me that my `LLVM` version was 'too high' and it would exclaim 'Hope this works!' upon every installation step. Very unnerving.

**Comment by christinem** [comment]
Cabal is an interesting beast, indeed. I still never got pandoc to work properly when I was on Windows because of some dependency conflict.

**Comment by christinem** [comment]
So it turns out diagrams did not install properly for me after all.....I can't select lecture or tutorial sections on the timetable. I can select the course from the right sidebar, but when I try to click the course on the left sidebar, the lecture and tutorial times don't expand out.

**Comment by Ian-Stewart-Binks** [comment]
@christinem Are you using the WebParsing? Sam hasn't added lectures or tutorials to the courses yet. This shouldn't be a result of in incorrect diagrams installation.

**Comment by christinem** [comment]
@Ian-Stewart-Binks interesting. But yes I am. Same instructions from the website, along with running the new parser.hs before running the database.hs

**Comment by david-yz-liu** [comment]
Oh, I think this "arithmoi" problem might have happened to me as well, but it ended up not hindering the compilation of Courseography. It would be good to add a note for this to the installation guide.

@Ian-Stewart-Binks is correct that the new database won't have lectures or tutorials. @christinem Otherwise, are you up and running?

**Comment by christinem** [comment]
@david-yz-liu yeah, everything else seems to be working for me now.

**Comment by david-yz-liu** [comment]
Including the Info modals? (This is how we can check if the database is working properly)

**Comment by christinem** [comment]
Yepp, info models on the graph are up and running as well!

**Comment by david-yz-liu** [comment]
Okay great. @christinem, can you please add a blurb in the Installation guide about the error you faced regarding "arithmoi", and to ignore it?

**Comment by christinem** [comment]
@david-yz-liu sure! Should I add the command that I used in order to get around it? Because otherwise it doesn't actually let you install diagrams altogether.

**Comment by david-yz-liu** [comment]
Hmmm really? Okay then.

**Comment by christinem** [comment]
It could have perhaps been something specific to my machine.... but I'll add it as something of a "just incase" clause.

**Comment by Ian-Stewart-Binks** [comment]
It looks like @christinem has added this to the installation guide. Are there any other tasks in this issue that need to be completed? Should we keep this open until all members of Courseography have successfully installed Diagrams?

**Comment by david-yz-liu** [comment]
I'll make a point of it on Monday.

BTW, I tried installing LLVM on my Windows machine, but couldn't get it recognized by Haskell. Christine's flag worked just fine. Odd...
