### ISSUE TITLE
Database.hs can't be run directly from database directory

### ISSUE THREAD

**Issue by christinem** [Courseography/courseography#395]
In order to run ```database.hs```, you have to run it from the ```hs``` directory, and then move the ```database1.sqlite3``` file manually to the database directory.

**Comment by david-yz-liu** [comment]
Have you tried running it again from the hs directory? The `dbStr` should be updated to put the database directly into the `Database` directory.

**Comment by christinem** [comment]
@david-yz-liu Ah you're right, it does put it directly into the Database folder now. My mistake!
