### ISSUE TITLE
Adding Testfile.svg to .gitignore

### ISSUE THREAD

**Issue by christinem** [Courseography/courseography#417]
I think we should add this file to .gitignore since it's automatically generated.

**Comment by Ian-Stewart-Binks** [comment]
Good idea!

**Comment by david-yz-liu** [comment]
@Ian-Stewart-Binks It would be nice to first give it a better name, put it in a good location, and then add it to the gitignore

**Comment by Ian-Stewart-Binks** [comment]
Sure thing. Where do you think the best place to put it would be?

**Comment by david-yz-liu** [comment]
Ah, put it in res. Remind me to talk to you about res the next time I see you.

**Comment by Ian-Stewart-Binks** [comment]
Sure.
