### ISSUE TITLE
Provide update functionality for SVG parser

### ISSUE THREAD

**Issue by Ian-Stewart-Binks** [Courseography/courseography#422]
If the SVG parser sees that a tuple that it is trying to insert is already in the database, then it should replace that tuple.

I have scanned [the persistent API](https://hackage.haskell.org/package/persistent-2.1.1.7/docs/Database-Persist-Class.html#v:repsert) to try to find a function that can help us accomplish this, however many of them do not.

I have come up with something along the lines of:
```
do sqlRects :: [Entity Rects] <- selectList [RectsRId ==. id_] []
    (if null sqlRects
     then insert_
     else replace (entityKey $ head sqlRects)) (Rects 1
                                                      id_
                                                      (toRational width)
                                                      (toRational height)
                                                      (toRational xPos)
                                                      (toRational yPos)
                                                      (fill style)
                                                      (stroke style)
                                                      (fill style == "#a14c3a")) 
```
I'm not so sure that I'm entirely happy with this proposed implementation.

Also, we would need to have some sort of uniqueness convention across tuples so that we can identify colliding tuples, as the Persistent generated primary key is not readily available for us based on data parsed from an arbitrary graph.

Alternatively, we could just replace the entire graph every time. We are trying to force uniqueness across graphs with the `gId` attribute in the database.

**Comment by david-yz-liu** [comment]
Update: seems easiest to just replace the entire graph if an old version is detected. We can detect "duplicates" by checking the graph titles.

**Comment by david-yz-liu** [comment]
I've changed the parser to drop all the graph-related data when running `courseography graphs`. Will need a better solution to support user-defined graphs (later).
