### ISSUE TITLE
Info button on Grid no longers works

### ISSUE THREAD

**Issue by david-yz-liu** [Courseography/courseography#436]

**Comment by Ian-Stewart-Binks** [comment]
This likely has something to do with lowercase IDs. I can look into this.

**Comment by christinem** [comment]
@Ian-Stewart-Binks Just to add to this, the delete course button does not work either. In fact, "Clear Courses" does not clear courses either. I have a feeling it might be related.

**Comment by Ian-Stewart-Binks** [comment]
We can add this line into the line 95 of common/util.js:
`data: {name : courseName.toUpperCase()},`. It works on the graph, but I can't test on the timetable due to #443.
@david-yz-liu thoughts?
