### ISSUE TITLE
New course times must be reconciled with grid table

### ISSUE THREAD

**Issue by david-yz-liu** [Courseography/courseography#437]
@foreverwander Half-hour branch has been updated; you can do a pull. You will most likely need to spend time updating packages on your machine, if you haven't been keeping up with master.

Afterwards, you must recreate the database (see installation guide). Once you have the server running, you can see the new JSON format by making an HTTP request http://localhost:8000/course?name=BIO120H1.

Currently, the table is not being updated correctly, as you would expect from the time format to have changed. You next major task should be to handle the new time format, including half-hour courses.

**Comment by foreverwander** [comment]
@david-yz-liu 
I have done a pull upstream half-hour and have successfully installed all of the haskell packages.

However, when I'm running the database.hs it says

WebParsing\TimeTableParse.hs:197:23:
Expected a constraint, but '[[T.Text]]' has kind '*'
In the type signature for 'processCourseTable' :+1: 
processCourseTable :: [[T.Text]] => IO <>

And no database files can be generated.

Sorry if this is something stupid on my part, but how would I be able to get pass this problem?

Thanks.

**Comment by david-yz-liu** [comment]
There was an error, I've updated the branch.

**Comment by david-yz-liu** [comment]
@foreverwander Ian made some updates, which I just merged into the half-hour branch. Unfortunately, you'll want to pull, and resolve any potential conflicts. We've settled on a format, though, so you should be able to make your remaining changes unobstructed.

**Comment by foreverwander** [comment]
@david-yz-liu Good news! No conflicts had to be resolved. I believe now everything is up to date and I'll start working on that right away.

**Comment by foreverwander** [comment]
@david-yz-liu just want to confirm. is the current format of tutorial times the format that you are going to keep? Now the lecture times are fixed but unfortunately nothing for tutorial works because of the different format of the list.

**Comment by david-yz-liu** [comment]
Leave the tutorial times alone for now. You have other things you should be doing.

You can use `git status` to view the status of your local repository.

**Comment by david-yz-liu** [comment]
@foreverwander seems to have both lectures and tutorial times working with the new format. Yay!
