### ISSUE TITLE
Timetable ID format

### ISSUE THREAD

**Issue by Ian-Stewart-Binks** [Courseography/courseography#443]
IDs in the timetable have periods. jQuery uses periods as meta characters, so these IDs cannot be used in the timetable.

**Comment by david-yz-liu** [comment]
Which IDs are you referring to?

**Comment by Ian-Stewart-Binks** [comment]
The new halfy IDs:
![id_error](https://cloud.githubusercontent.com/assets/6301000/6605993/bd951688-c80a-11e4-891d-c2df19638953.png)

**Comment by Ian-Stewart-Binks** [comment]
To reproduce: add this to 95 of common/util.js:
`data: {name : courseName.toUpperCase()}` (this is a quick fix to get the course, currently proposed in #436)
then select a lecture for CSC104, and then deselect the selected lecture.

**Comment by david-yz-liu** [comment]
@Ian-Stewart-Binks Are you working on this? I started working on this a little while ago before I saw your updates... I will push what I've done.

**Comment by Ian-Stewart-Binks** [comment]
@david-yz-liu I wasn't working on this. Thanks for making the changes.

**Comment by Ian-Stewart-Binks** [comment]
@david-yz-liu This fix looks trickier, as it appears that the `.` is taken from the double that each `Time` is stored as in the `parseJSON` function.

We could either store `Time` as a string and convert the `.` to a `-` before insertion into the database, or we could convert all `.` to `-` when making the JSON string into a response. I haven't tried either of these out, so I am not certain that they will work.

How do you think we should proceed?

**Comment by david-yz-liu** [comment]
I'd like to keep the `Time` a double for now. I'm happy to do the substitution you suggested when creating the JSON response.

**Comment by Ian-Stewart-Binks** [comment]
With substitution, I will have to replace periods that infront of and behind digits. Otherwise, course descriptions would have no periods.

I'll try to think of a better way.

**Comment by david-yz-liu** [comment]
Is it not possible to just replace periods within the time string?

**Comment by Ian-Stewart-Binks** [comment]
We can convert the doubles to strings before using parseJSON on the `times` and then replace `.` with `-`. This would be done in the parsing process, not the response.

Also, what is `time_str` used for?

**Comment by david-yz-liu** [comment]
1. Why can't this be done when defining the `toJSON` function?
2. I think `time_str` was used when populating the old timetable tab

**Comment by Ian-Stewart-Binks** [comment]
1. Mmm, yes sorry that's what I meant.
