### ISSUE TITLE
getCourseObject is not working in the timetable

### ISSUE THREAD

**Issue by Ian-Stewart-Binks** [Courseography/courseography#447]
I may be wrong, but `getCourseObject` uses the inner html of the timetable cells. The inner html has recently been changed, and as such `getCourseObject` no longer works.

**Comment by foreverwander** [comment]
getCourseObject now uses the .data('courseName') stored with each cell instead

**Comment by david-yz-liu** [comment]
@Ian-Stewart-Binks @foreverwander It works now, but the CSS needs to be tweaked to display the correct on-hover behaviour. Currently, the class selector "hover-time" is overridden.
