### ISSUE TITLE
Graph: Courses currently not 'initially takeable'

### ISSUE THREAD

**Issue by Ian-Stewart-Binks** [Courseography/courseography#472]
Courses that have no prerequisites, such as CSC108, are currently not initially takeable.

**Comment by christinem** [comment]
@Ian-Stewart-Binks Really? It seems to look like it's initially takeable to me. It's in the initiallyTakeable array and the style of the node is the same. The only ones that don't seem to have the right style are CSC300, CSC200, and Lin1 (I cross-referenced with the live graph to double check).

**Comment by Ian-Stewart-Binks** [comment]
@christinem Go to https://courseography.cdf.toronto.edu/graph and clear your cookies.

**Comment by Ian-Stewart-Binks** [comment]
*Clearing cookies is vital ingredient for issue.

**Comment by christinem** [comment]
Ahhh, you're right, clearing cookies bring the issue back up. 
Funny thing is, once you select an initially takaeble course, then deselect it, it becomes the proper style. 
I can take a look at this.
