### ISSUE TITLE
Cookie Limit Too Low On CDF

### ISSUE THREAD

**Issue by Ian-Stewart-Binks** [Courseography/courseography#500]
Once enough cookies are stored, the CDF hosted Courseography responds with a 400 error, and the message "Request Header Or Cookie Too Large".

**Comment by david-yz-liu** [comment]
@Ian-Stewart-Binks Could you try again, please?

**Comment by Ian-Stewart-Binks** [comment]
Yes. Works fine now!

**Comment by david-yz-liu** [comment]
Thanks, @Ian-Stewart-Binks
