### ISSUE TITLE
Courseography Logo

### ISSUE THREAD

**Issue by Ian-Stewart-Binks** [Courseography/courseography#502]
Courseography needs a logo. This was brought up in the Courseography meeting on March 30th.

**Comment by david-yz-liu** [comment]
@jmatholia @pkukulak I will buy things with a logo if you make one. Just saying.

**Comment by christinem** [comment]
This needs to happen :)

**Comment by pkukulak** [comment]
I can pitch a few rough designs after the demos on Thursday. Keep in mind that I am not a graphic designer by any stretch of the imagination.

**Comment by david-yz-liu** [comment]
That would be awesome! I'm not either!

**Comment by david-yz-liu** [comment]
@jmatholia @pkukulak More incentive... If you complete a logo by Monday, I can put it on the poster for Research in Action!

**Comment by christinem** [comment]
I'll try and play around with something too :)

**Comment by jmatholia** [comment]
@david-yz-liu @pkukulak I have started working on it, this is what I have so far: 
![image](https://cloud.githubusercontent.com/assets/9491656/7104231/1873cd68-e09f-11e4-92f2-7336f0fda0b8.png)
Let me know what you think, feel free to be harsh. I haven't tried a globe like C yet. We were thinking black and red, but I realized the background for the nav bar is black so I also tried: 
![image](https://cloud.githubusercontent.com/assets/9491656/7104313/d2688ace-e0a4-11e4-8a91-d6b076f7d304.png)
![image](https://cloud.githubusercontent.com/assets/9491656/7104331/3b608134-e0a6-11e4-899c-ca595d10c40e.png)

**Comment by jmatholia** [comment]
@david-yz-liu @pkukulak Some changes: 
![image](https://cloud.githubusercontent.com/assets/9491656/7104493/334213ca-e0b3-11e4-93b8-53ae3d6ef831.png)
![image](https://cloud.githubusercontent.com/assets/9491656/7104494/4e1b5468-e0b3-11e4-9b7e-279a3f8d1231.png)

**Comment by pkukulak** [comment]
Nice :) More or less how I pictured it. I think it would look a bit better if the compass had a more pronounced border and didn't overlap with any characters, though I really like the slight tilt it's sitting on. I have no idea what the limitations are, but I think it would also be really cool if the compass was stylized as a cursive "o" as well.

Did you get a chance to play with font sizes, as well? At the moment, it sort of looks like "Curseography". Perhaps the "C" could be the same size as it is now, whereas all other characters are smaller and attached to the compass that sits inside the "C"?

I'm glad you liked my idea enough to make this. I really like where it's headed.

**Comment by david-yz-liu** [comment]
Looking cool. Agree with @pkukulak - perhaps also try playing around with making a thicker border around the "O" to give it more definition.

Not a big fan of the colours, and not tied to a "black" nav bar. I always pictured the compass having a light beige/brown colour, which is more traditional. Blood-red and black is a little too extreme for Courseography.

**Comment by christinem** [comment]
I think it looks cool too! I agree with a thicker border around the O, because on any background that's not dark, it doesn't stand out. Are there also other fonts for the cursive we could play with perhaps, out of curiosity? I do like the tilt on the second one.

**Comment by jmatholia** [comment]
@david-yz-liu @pkukulak @christinem Thanks for the feedback! I am trying a more pronounced border for the compass (possibly cursive), a different colour scheme and possibly a different font/font sizes.

**Comment by jmatholia** [comment]
@david-yz-liu @pkukulak @christinem  @Ian-Stewart-Binks @foreverwander 
Let me know what you think: The font is a little bigger for the "urseography" part and more aligned with the compass, different colour scheme, and a more pronounced border.
![image](https://cloud.githubusercontent.com/assets/9491656/7122470/a76d78fc-e1e9-11e4-82df-c2d8750c1d14.png)
![image](https://cloud.githubusercontent.com/assets/9491656/7122519/0123801c-e1ea-11e4-80b5-71209f058a13.png)
![image](https://cloud.githubusercontent.com/assets/9491656/7122450/84dc3328-e1e9-11e4-878e-462e1fb02084.png)
I was not able to try other fonts yet, but these are some other cursive fonts, let me know if you like any of them and I can try them out: 
1. ![image](https://cloud.githubusercontent.com/assets/9491656/7123039/5c8ad452-e1ed-11e4-9c3b-ba095565a0c5.png)
2. ![image](https://cloud.githubusercontent.com/assets/9491656/7123055/71d89b1e-e1ed-11e4-8621-7f338b13cd82.png)
3. ![image](https://cloud.githubusercontent.com/assets/9491656/7123193/659bce6a-e1ee-11e4-9e5a-d4dc191f7597.png)
4. ![image](https://cloud.githubusercontent.com/assets/9491656/7123209/9c7e5d26-e1ee-11e4-9513-c6775362ddf7.png)
5. ![image](https://cloud.githubusercontent.com/assets/9491656/7123217/a8c5f5da-e1ee-11e4-9d6a-d03089c9c1ce.png)

**Comment by pkukulak** [comment]
I love the first one. It looks great with the "o" filled in. I also think it's the nicest of the cursive fonts.

**Comment by christinem** [comment]
I agree with @pkukulak about the first one. The colours are great! I think #3 would be another good font, but the original font is good well. Awesome job!

**Comment by david-yz-liu** [comment]
I like the original font as well, though I wish it were a bit less thick.

**Comment by jmatholia** [comment]
I'm glad you all like it!
@david-yz-liu (or anyone else who knows) As I was trying to see if I could make the text thinner, I realized that I downloaded this font a while ago off the internet. The font's name is Armonioso, and it is free for personal use (i.e. not for commercial use). Is this an issue for courseography? We don't technically make money using it.

**Comment by jmatholia** [comment]
Also the liscence says we must use the credit line: "Font: Armonioso Family by Zetafonts -http://www.zetafonts.com/collection/323". Would this be in our HTML?

**Comment by david-yz-liu** [comment]
Eh, let's try to pick a different font for now.

**Comment by jmatholia** [comment]
Aww man okay, I will try some of the other ones.

**Comment by jmatholia** [comment]
This is what I have so far with the other fonts:
![image](https://cloud.githubusercontent.com/assets/9491656/7130840/e3edea5e-e244-11e4-8a11-0e831e7089d7.png)
![image](https://cloud.githubusercontent.com/assets/9491656/7130844/f357c410-e244-11e4-8214-b10b7014ccce.png)

**Comment by david-yz-liu** [comment]
I like the C of the second one but the rest of the first one. Could you make the font of the first one just a little smaller, and perhaps connect the first 'o' to the 'u'? (Designer work is a pain...)

**Comment by pkukulak** [comment]
I would also be interested to see how it looks with "Co" in the foreground, i.e. "urseography" a bit smaller in fontsize.

**Comment by jmatholia** [comment]
After a "logo sprint" with David, we decided that the following would be a good full logo, to ensure that it is never read as Cursography: 
![image](https://cloud.githubusercontent.com/assets/9491656/7145658/d212bdec-e2bb-11e4-9263-393b2bf98625.png)

and this would be a good favicon:
![image](https://cloud.githubusercontent.com/assets/9491656/7145718/6213e5ba-e2bc-11e4-9017-dfa9060fb82c.png)

**Comment by christinem** [comment]
I really like it! Especially the font. Great job @jmatholia!! :)

**Comment by foreverwander** [comment]
@jmatholia  It looks awesome!!! I especailly like the line around the compus in the favicon, gives it a leathery feel :D

**Comment by Ian-Stewart-Binks** [comment]
Nicely done.
