### ISSUE TITLE
Grid: Conflicts are not rendered correctly

### ISSUE THREAD

**Issue by Ian-Stewart-Binks** [Courseography/courseography#509]
When a conflict is selected in the grid, only one lecture time shows up as 'in conflict'.

**Comment by david-yz-liu** [comment]
@Ian-Stewart-Binks I'm not sure I understand what you mean by "one lecture time shows up as 'in conflict'"

**Comment by Ian-Stewart-Binks** [comment]
Try adding CSC108 and CSC148 in the winter section, when they conflict. The code will try to make both sections of the first chosen course red, or 'in conflict'. It does the first section, runs some other code, then does the second one, then runs some more code. After the first section is turned red (or is set to be in conflict), an error is thrown and the second section never goes in conflict.

The error occurred right after the section was set to be in conflict, when the code tries to resolve the 'satisfied' attribute. The fix in #523 fixes the piece of code that threw the error.

**Comment by david-yz-liu** [comment]
Ah, I see.
