### ISSUE TITLE
2015-2016 Calendar Update

### ISSUE THREAD

**Issue by Ian-Stewart-Binks** [Courseography/courseography#520]
[The CSC graph needs to be updated with the 2015-2016 changes.](http://www.artsandscience.utoronto.ca/ofr/calendar/crs_csc.htm)

List of potential changes:
- [x] CSC466 needs to be added to the graph
- [x] CSC485 now has CSC207/209 instead of just 209
- [ ] Grade prerequisites for 207/236/258
- [x] CSC448H1 has only 236 for prereq now
- [x] CSC456H1 has 436 instead of 350
- [ ] CSC165: 
    Prerequisite: CSC108H1/CSC120H1 OR satisfy corequisite
    Corequisite: (CSC108H1/CSC120H, MAT137Y1/MAT157Y1)/ CSC148H1

**Comment by david-yz-liu** [comment]
#550 addresses the above four points; I don't think grade prerequisites are really ever going to be supported; dealing with corequisites is something we might look at later, but it'll be a new feature, so it's not urgent.
