### ISSUE TITLE
Text for tooltip not aligned properly when zooming on browser

### ISSUE THREAD

**Issue by christinem** [Courseography/courseography#526]
When you change the zoom in the browser, the "Info" text on the tooltip becomes unaligned. 

Example:

![img1](https://cloud.githubusercontent.com/assets/5077973/7104883/eca7815c-e0cb-11e4-82ef-8b7c9fde0a99.png)
![img2](https://cloud.githubusercontent.com/assets/5077973/7104884/ef15ffea-e0cb-11e4-9b3a-0963bfe4f48c.png)

**Comment by Ian-Stewart-Binks** [comment]
Interesting. This doesn't happen for me on https://courseography.cdf.toronto.edu/graph

**Comment by christinem** [comment]
@Ian-Stewart-Binks hah, seems like it's a browser-independent issue. It's fine on Chrome and Firefox but the above is what shows on Safari. Not quite sure why that happens on Safari, the more you zoom, the more unaligned it gets. Haven't tested on IE yet.

**Comment by Ian-Stewart-Binks** [comment]
Ah yes, I believe Safari has been troublesome before.

I believe that it was decided last summer to only support Chrome and FireFox, just like MarkUs (or something along those lines). This doesn't appear to have been written anywhere though, so right now we officially do not support browsers. Er... I mean, we do not officially support browsers :-)

**Comment by david-yz-liu** [comment]
As long as Chrome and FireFox are okay, I'm happy.
