### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by Ian-Stewart-Binks** [Courseography/courseography#535]
Courseography needs a favicon. Right now, https://courseography.cdf.toronto.edu/graph displays the sad little blank piece of paper.

**Comment by jmatholia** [comment]
Sorry didn't realize there was another issue for the favicon. This is what we have: 
![image](https://cloud.githubusercontent.com/assets/9491656/7145830/fdf95dca-e2bc-11e4-947e-5b5a0b7264c7.png)

**Comment by david-yz-liu** [comment]
@jmatholia I'm about to add it to Courseography. I think we should pick a background colour, or something; looks odd as purely white background, but I think it's even odder with a transparent background. 16x16 is pretty small.
