### ISSUE TITLE
Reset Graphs: Region Opacity Change

### ISSUE THREAD

**Issue by Ian-Stewart-Binks** [Courseography/courseography#546]
The opacity of the regions changes when the 'Reset Graphs' button is pressed (only works when a course is selected and the reset button is pressed). Clicking the 'CSC' button in the Graphs tab of the sidebar reverses this...

**Comment by david-yz-liu** [comment]
I believe this is one of the things Christine's PR fixes.

**Comment by Ian-Stewart-Binks** [comment]
Mmm. Yes, it looks so. Apologies!

**Comment by david-yz-liu** [comment]
No worries.
