### ISSUE TITLE
Broken Info Modals

### ISSUE THREAD

**Issue by christinem** [Courseography/courseography#552]
There seem to be some info modals that are broken on the graph. The ones I identified are:

Calc1, Sta1, Sta2, Lin1, CSC200, ECE385

I get the console error: `Uncaught TypeError: Cannot read property 'lectures' of null`, on `course.js: 83`.

**Comment by david-yz-liu** [comment]
Hmm. The problem for CSC200 is it's a Y1 not H1, so the search isn't working properly. Not entirely sure about ECE385.

For the math courses, we'll probably want to do what we did for the 165/240 and 236/240 nodes.

**Comment by david-yz-liu** [comment]
They do work now, though they only show the first alternative. We'll have to come up with a better solution to display multiple courses in the modal.
