### ISSUE TITLE
Add development info

### ISSUE THREAD

**Issue by arkon** [Courseography/courseography#555]
I have no idea what to install and how to get started with helping out on this project since there's no documentation on what framework is used, how the project is structured, etc.

**Comment by david-yz-liu** [comment]
Here's a link. https://github.com/Courseography/courseography/wiki/Installing-Courseography

Perhps we'll add it to the README.

**Comment by arkon** [comment]
Ooh yeah, it'd be nice if there was a link to it in the "Get Involved" section of the README.

**Comment by david-yz-liu** [comment]
Go for it!
