### ISSUE TITLE
Course Planner Site

### ISSUE THREAD

**Issue by Ian-Stewart-Binks** [Courseography/courseography#556]
What should we do with [Course Planner](http://www.cs.toronto.edu/~liudavid/rqs/planner.html), now that Courseography is hosted elsewhere?

We could redirect to the new one, or simply notify the user that they're using an outdated version.

**Comment by david-yz-liu** [comment]
I'll redirect it.

**Comment by arkon** [comment]
@david-yz-liu Seems like some people are still going to the old site.

**Comment by david-yz-liu** [comment]
Done, finally!
