### ISSUE TITLE
Update File Structure Overview

### ISSUE THREAD

**Issue by Ian-Stewart-Binks** [Courseography/courseography#562]
The wiki page "File Structure Overview" is out of date. We either need to make sure that this file is update to date after every merge, or get rid of it.

**Comment by david-yz-liu** [comment]
You're right; @elliotsj's idea of separate READMEs seems like a good way to go.

**Comment by elliottsj** [comment]
I've edited out the file structure overview in favour of a less-formal overview: https://github.com/Courseography/courseography/wiki/Application-Overview

Detailed documentation for each module should be written at the top of each file as [Haddock module descriptions](https://www.haskell.org/haddock/doc/html/ch03s03.html).

**Comment by david-yz-liu** [comment]
Thanks, @elliottsj!
