### ISSUE TITLE
Use npm + webpack for CommonJS modules in the browser

### ISSUE THREAD

**Issue by elliottsj** [Courseography/courseography#567]
Currently, JavaScripts are loaded ad hoc by [inserting a different list of `<script src="..."></script>`s for each page](https://github.com/Courseography/courseography/blob/d20e05ad0c82f865c6c021db80f559f5a865a445/hs/Scripts.hs), with each script defining various `var`s and `function`s called by later scripts.

A better solution is to use a [CommonJS](http://webpack.github.io/docs/commonjs.html) module bundler such as [webpack](http://webpack.github.io/docs/) so that individual scripts can explicitly load their dependencies.

For example, [course.js calls `updateSelectedLectures`](https://github.com/Courseography/courseography/blob/d20e05ad0c82f865c6c021db80f559f5a865a445/public/js/common/objects/course.js#L194) (which is [defined in timetable_util.js](https://github.com/Courseography/courseography/blob/d20e05ad0c82f865c6c021db80f559f5a865a445/public/js/grid/timetable_util.js#L5)), but this only works because [timetable_util.js occurs before course.js in Scripts.hs](https://github.com/Courseography/courseography/blob/d20e05ad0c82f865c6c021db80f559f5a865a445/hs/Scripts.hs#L43). Better would be:
```
// course.js
...
var updateSelectedLectures = require(‘../timetable_util’).updateSelectedLectures;
...
updateSelectedLectures();
...
```

---

The way we’d go about doing this is to add NodeJS as a dependency of the project, `npm install` all of the frontend dependencies (jquery, bootstrap, react), and use a tool like Brunch (http://brunch.io/) to bundle JavaScripts into a single entry for each page (e.g. `static/js/search.js`, `static/js/graph.js`). In development, Brunch will need run concurrently with `runhaskell server.hs`, so we’ll need something like a `Procfile` (via https://github.com/strongloop/node-foreman) to run multiple processes easily.

**Comment by david-yz-liu** [comment]
The JavaScript files are quite messy, but I'm not convinced adding this kind of tooling is necessary right now. Effort is better spent improving the code.

**Comment by elliottsj** [comment]
The reason I bring up webpack is that I think it's a good first step to make the browser components more modular, predictable, and testable: this usually means less development effort.

Eventually, I believe the best way to structure Courseography is to largely decouple the Haskell service from the web front end, with a view layer like [React](https://facebook.github.io/react/) handling almost all templating and UI interactions that are currently handled imperatively using a lot of manual DOM manipulation with jQuery. (Yep, [React can handle SVG elements](https://facebook.github.io/react/docs/tags-and-attributes.html#svg-elements)). The frontend would probably live in a separate repository on GitHub.

I think the benefits of moving toward this structure far outweigh the drawback of extra tooling:
- CommonJS modules (like Haskell's `import` statement)
- Compose views declaratively (kind of like Haskell's BlazeHtml)
- Able to use [npm modules](https://www.npmjs.com/)
- Easily unit test modules with tools like [Jest](https://facebook.github.io/jest/)

**Comment by Ian-Stewart-Binks** [comment]
I think it might be good to start something like this. We definitely need to start testing.
@david-yz-liu In what ways should we start improving the code? When is it time to start implementing this issue?

**Comment by david-yz-liu** [comment]
@Ian-Stewart-Binks I think we should start talking about testing offline. And we can implement a module system, too.

**Comment by david-yz-liu** [comment]
Okay, so I think we should use AMD modules; they seem easier to get started with because they don't involve a compilation step.

@Ian-Stewart-Binks you've already done some work with QUnit, so why don't you continue with that for now?

**Comment by arkon** [comment]
@elliottsj Aren't you really against AMD modules?

**Comment by elliottsj** [comment]
@arkon I think CommonJS is better since it's less verbose, more readable, and with proper tooling (e.g. webpack), you have more control over how scripts are loaded by the browser.

I assume you'll be using [RequireJS](http://requirejs.org/) as your AMD module loader. IMO, the 'benefit'  of using RequireJS (i.e. avoiding the compilation step) is outweighed by the complexity that RequireJS introduces: e.g. [module names](http://requirejs.org/docs/api.html#modulename), [shims](http://requirejs.org/docs/api.html#modulename); you just wouldn't have to worry about these if you use a CommonJS module bundler.
