### ISSUE TITLE
Graph titles can't have spaces (?)

### ISSUE THREAD

**Issue by david-yz-liu** [Courseography/courseography#578]
In the graph side bar, I had a graph named "Computer Science" not showing up in the list of selectable graphs. I changed the name to "ComputerScience" and it appeared.

@christinem I wonder if you can reproduce this.

**Comment by christinem** [comment]
@david-yz-liu yeah I can reproduce it, and I figured out why too. It's the way I assign IDs to the graph buttons. As you can see below:

![courseography_-_graph](https://cloud.githubusercontent.com/assets/5077973/7336019/b4b6704e-ebb3-11e4-8b17-d58b9e5802e4.png)

There's a space in the ID which breaks it. I'll change how the IDs are assignment. Perhaps maybe just the first word of the graph title.

**Comment by david-yz-liu** [comment]
First word may not be unique - I'd go with using the graph id rather than names.
