### ISSUE TITLE
Stop using Pandoc

### ISSUE THREAD

**Issue by david-yz-liu** [Courseography/courseography#594]
Okay, the fact that @christinem, @jmatholia, @foreverwander, and now @akbiggs are all having the same problem means that I'm the odd one out when it comes to Windows installation.

One possibility is to simply rewrite the About and Privacy pages in some other format to eliminate the need for conversion.

My favoured solution, however, is to swap out Pandoc for the much lighter [`markdown`](https://hackage.haskell.org/package/markdown) package.

If someone I tagged on Windows could try this out and see if this works, that would be fantastic.

**Comment by akbiggs** [comment]
Okay, I will try out the markdown package. Thanks!
