### ISSUE TITLE
Redesign the modal

### ISSUE THREAD

**Issue by david-yz-liu** [Courseography/courseography#608]
1. Make the box smaller.
2. Change the colours (related to #607)
3. Make the font smaller.
4. (For the FB posting) Make the buttons centered.

**Comment by cchens** [comment]
We've been talking about the possibility of implementing [Material Design](http://callemall.github.io/material-ui/#/). The modal in particular looks a lot better when it's elevated from the rest of the page. Check the Slack files for some mockups @arkon did.

**Comment by arkon** [comment]
[These dialogs](http://callemall.github.io/material-ui/#/components/dialog) to be exact.
