### ISSUE TITLE
Hybrid/Override Issue

### ISSUE THREAD

**Issue by Ian-Stewart-Binks** [Courseography/courseography#621]
I'm experiencing some difficulty when selecting a course (overridden) and then selecting a prerequisite for that first course. The edge from the prerequisite's hybrid to the first node doesn't light up.

To reproduce:
1. Reset CSC graph.
2. Select CSC420.
3. Select CSC263/265.

Also, in the statistics graph:
1. Reset STA graph.
2. Select CSC414.
3. Select CSC108/120/148.

I suspect that this is a bug, because I have been able to make the edge light up.

**Comment by david-yz-liu** [comment]
Should also look into how the IDs are generated for the hybrid nodes. Plus, the relationships for some of the hybrids are hard-coded, so some of them might need to be updated.

**Comment by david-yz-liu** [comment]
This seems no longer to be an issue.
