### ISSUE TITLE
Text cut off in Grid Images when posting to Facebook

### ISSUE THREAD

**Issue by christinem** [Courseography/courseography#659]
On the live version (courseography.cdf.toronto.edu), it looks as though any course on the grid has the text cut off at the top when trying to post to Facebook.

![courseography_-_grid](https://cloud.githubusercontent.com/assets/5077973/8446672/1ca967e6-1f7c-11e5-885b-b3c0083249fc.png)

It ends up looking the same when it's posted to Facebook as well.

**Comment by david-yz-liu** [comment]
Note: won't be technically closed until the next time I update CDF, but it was fixed in master.
