### ISSUE TITLE
Computer Science Focuses Accessible When Other Graphs Are in View

### ISSUE THREAD

**Issue by Ian-Stewart-Binks** [Courseography/courseography#664]
When I'm looking at another graph, I can still access the CS focuses. Is this the behaviour that we want?

**Comment by cchens** [comment]
This wouldn't apply right now because there aren't enough graphs, but some focuses do require courses from other departments, in which case this behaviour might make sense

**Comment by christinem** [comment]
Most likely not. I think we have discussed this St some point. The best option probably is to have the main sidebar tab be the graphs tab, and have to focuses tab disabled unless we are on the CS graph.

**Comment by Ian-Stewart-Binks** [comment]
@christinem I agree.

**Comment by david-yz-liu** [comment]
Yes, this is a fine solution. If I recall correctly, there is some attribute which stores the name of the current graph, so it should be easy to show/hide that tab based on that.

**Comment by christinem** [comment]
@david-yz-liu we have a cookie that stores the active graph id, and from this we can easily determine which graph is active. I can fix this issue.

**Comment by david-yz-liu** [comment]
Okay, thanks @christinem!
