### ISSUE TITLE
CSC200**Y1** info modal on Grid doesn't work

### ISSUE THREAD

**Issue by david-yz-liu** [Courseography/courseography#667]
Sending a bad request to the server: name=CSC200Y1H1. Should look for the how the correct course code is being set in the HTML and use that.

**Comment by david-yz-liu** [comment]
Contained in #552 already

**Comment by Ian-Stewart-Binks** [comment]
The bug that David mentions in this pull request appears in the Grid. The code in the Grid can determine the suffix for a course (Y1, H1), but the Graph cannot. We can limit the IDs in the Grid to 6 characters so that the course retrieval functionality is identical for both the Graph and the Grid.
