### ISSUE TITLE
Update Grid Timetable Database on Live Server (and add a footer of last date updated)

### ISSUE THREAD

**Issue by christinem** [Courseography/courseography#682]
There have been a bunch of time and lecture changes to the Arts and Science timetable listings since the last time the timetable database was updated (I've already noticed a few discrepancies in the Computer Science timetable), and since courseography has been advertised around and people are using it, we should do an update of the database on the live server. It would also be good to have a footer of the date it was last updated, so that anyone using it is aware how current the timetable grid information is.

**Comment by david-yz-liu** [comment]
@christinem I believe I've updated the database, but I'm not sure what discrepancies there were; if you could check to see if things are up to date, that would be great. 

I've been asked to import the Excel spreadsheet DCS is using internally to track its courses, so the database will likely update again.

As for a "last updated" footer, that's a great idea. I'd like to add a database field for that.

**Comment by christinem** [comment]
@david-yz-liu It looks like the discrepancies are now gone. There were changes to all the timetables on July 8th that weren't reflected on Courseography before, but now it seems to be good. 

As well, the Computer Science times seem to be in sync with the internal spreadsheet.

**Comment by david-yz-liu** [comment]
Thanks, @christinem! I'll close this issue and add a note about a "last updated time" in the footer issue.
