### ISSUE TITLE
Issue with Export Feature

### ISSUE THREAD

**Issue by christinem** [Courseography/courseography#714]
I seem to be having problems when trying to use the `Export` feature. When I press Export, I get no new modal popping up, and I get this message in the Javascript console:

<img width="1278" alt="screen shot 2015-09-17 at 1 09 07 pm" src="https://cloud.githubusercontent.com/assets/5077973/9940348/523ac6ee-5d3d-11e5-9bb2-7a262c88eebc.png">

The log message in the command line is:

```
"Waiting for process..."
"Process Complete"
127.0.0.1 - GET /image 1.1 500 http://localhost:8000/graph
```

The svg image also remains in the `hs` directory and does not get deleted. My master is updated to the latest files.

**Comment by pkukulak** [comment]
I was just working through this error. My problem was that I didn't have ```imagemagick``` installed; every time the chain reached the point at which the process for ```convert``` is created and called, the program would halt and throw an error.

**Comment by Ian-Stewart-Binks** [comment]
@pkukulak I'm not certain that the image generation code correctly reads error messages when invoking shell commands. Is this still true?

This area in the code has been a source of confusion for many of us, and could use some improvement on the error reporting side.

@christinem The image generation code should delete the image after. When I created this code in the winter, I recall this being a temporary issue that was resolved. What is the cause of the file not being deleted?

**Comment by christinem** [comment]
@pkukulak interesting, I am pretty sure I had it installed but I'll give it another look.
@Ian-Stewart-Binks The issue never really got resolved on my end. It seems to work fine on @david-yz-liu 's machine and @cchen 's machine however. The particular errors I receive in my original post have been consistent since I first brought this issue up last semester. I'll try Phil's suggestion and give it a deeper look myself to try and rule out any machine-dependent errors.

**Comment by christinem** [comment]
Update: Looks like @pkukulak 's suggestion was correct - I installed imagemagick and I am now able to get the modal open, and the svg images don't remain in the `hs` folder anymore. However, the image looks quite funny:

<img width="913" alt="screen shot 2015-09-27 at 10 35 03 pm" src="https://cloud.githubusercontent.com/assets/5077973/10126934/37ab24e4-6568-11e5-9700-dfbfd510e266.png">

My suspicion is there might be something weird with my Image Magick.

**Comment by Ian-Stewart-Binks** [comment]
We need to read in the error message from that process and print it to the user(/developer).

Can be done here: https://github.com/Courseography/courseography/blob/master/hs/ImageConversion.hs#L53

I made a note about using `hGetContents` when I was trying to implement something similar at the time. (Or perhaps I was trying to implement the exact same thing, memory does not serve well.)
