### ISSUE TITLE
Doubles of courses in Grid

### ISSUE THREAD

**Issue by christinem** [Courseography/courseography#716]
Currently, on the live version, there are doubles of every single course on the Grid (do a search for any course and you'll see doubles). This does not happen in my local version however.

**Comment by Ian-Stewart-Binks** [comment]
@david-yz-liu 
![screenshot from 2015-10-04 19 35 46](https://cloud.githubusercontent.com/assets/6301000/10270942/2736afc2-6acf-11e5-8a47-d3ab2bfbf8be.png)

**Comment by david-yz-liu** [comment]
Thanks, this has been fixed.
