### ISSUE TITLE
Grid conflict overlay blocks search box

### ISSUE THREAD

**Issue by pkukulak** [Courseography/courseography#724]
When conflicting courses are selected in the grid, the warning overlay prevents the user from searching for more courses until one of the conflicting courses is removed.

**Comment by Ian-Stewart-Binks** [comment]
Doesn't happen for my display, 1920x1080.

**Comment by pkukulak** [comment]
I figured it would probably be fine on larger resolutions, but for those with - for instance - 1280x800 13 inch Macbook Pros, it would probably suffice for the warning to fade after a few moments, since conflicting courses remain marked as red in the timetable.

**Comment by Ian-Stewart-Binks** [comment]
Agreed. Or something similar. That thing is an eyesore.
