### ISSUE TITLE
Timetable search doesn't work with full year courses.

### ISSUE THREAD

**Issue by ryanfan** [Courseography/courseography#732]
Example:  Choose MAT department and type "MAT13" since MAT133 is a full year and MAT135 is a half year course

**Comment by Ian-Stewart-Binks** [comment]
@ryanfan I'm not sure I'm going this right- do you mean on the live instance or the development version?

I get this from the live instance:
![screenshot from 2015-10-07 16 48 35](https://cloud.githubusercontent.com/assets/6301000/10350673/5f5632d8-6d13-11e5-9003-09df61923e2d.png)

**Comment by ryanfan** [comment]
Yes, I was getting that.  To me, it seemed a little confusing, but I do know that the headers are created before the timetables are shown.  Sorry if my issue didn't make it clear.

**Comment by ryanfan** [comment]
I was seeing if I could reuse the React components but it doesn't seem that I can do that easily.
