### ISSUE TITLE
Navigation Bar

### ISSUE THREAD

**Issue by c4xuange** [Courseography/courseography#738]
Navigation bar readjusts when the browser is shrinked

**Comment by Ian-Stewart-Binks** [comment]
Hey @c4xuange, thanks for the bug report. Do you mind providing both a screenshot of the behaviour and steps to reproduce? Thanks.

**Comment by c4xuange** [comment]
<img width="598" alt="screen shot 2015-10-27 at 3 06 05 pm" src="https://cloud.githubusercontent.com/assets/11496501/10769418/52298746-7cbc-11e5-8a37-2b2d9d694f5b.png">

When you readjust the browser size, the buttons collapse onto a second line and lose functionality
