### ISSUE TITLE
Notify HaXml of compilation error

### ISSUE THREAD

**Issue by Ian-Stewart-Binks** [Courseography/courseography#774]
If I recall correctly, we have the HaXml code in our codebase as it needs to be modified to compile on Windows when using stack instead of cabal. We should let HaXml know this such that they can fix it, or to see if they have a better fix than our current fix.

Our current fix is to modify their code in such a way that it compiles correctly, and as such we have all HaXml code in the Courseography codebase.

**Comment by david-yz-liu** [comment]
This isn't a bad idea, but I don't have time to do this and our current solution is working just fine. Eventually we'll stop using HaXml altogether.
