### ISSUE TITLE
Graph buttons view in sidebar needs to be scrollable

### ISSUE THREAD

**Issue by christinem** [Courseography/courseography#787]
As we're adding more graphs, we need to make the sidebar be able to scroll through all the graph buttons in the sidebar - right now they just start appearing outside of the sidebar.

![screen shot 2016-02-06 at 1 51 29 am](https://cloud.githubusercontent.com/assets/5077973/12865192/2f73aa62-cc74-11e5-95cf-803a0431143a.png)

**Comment by arkon** [comment]
They should probably also be sorted alphabetically.

**Comment by qasim** [comment]
While stuff is happening here, should the padding / margins / borders in this component be cleaned up as well?

**Comment by R0ss** [comment]
It's fixed!
