### ISSUE TITLE
Logic bug in focusPrereqs

### ISSUE THREAD

**Issue by ryanfan** [Courseography/courseography#838]
There is some sort of missing case in `focusPrereqs`.
The issue can be replicated like this:
1.Make sure graph is cleared and nothing is selected.
2.Click on CSC148
3.Hover over CSC258
4.The edge from CSC148 to CSC258 is not `missing`

**Comment by david-yz-liu** [comment]
Ah, is this what you meant last meeting? It is a change in logic, but I'm pretty sure I did that deliberately. I guess the idea is that CSC148 is already marked as "overridden", and students don't need to be reminded of that whenever they want to take more courses that require CSC148.

In other words, a missing prereq is less important than having clicked on the node, for the purpose of future planning.

**Comment by ryanfan** [comment]
Yes, this is what I meant, I didn't want to sidetrack the meeting.
Ok, I understand what you're saying.  I may just be used to how it was before, but I find it a bit odd that two red nodes are not connected by a red edge.

**Comment by david-yz-liu** [comment]
Yeah, I know what you mean. However, the course appears red because of a different missing prerequisite. (If all of its prerequisites are overridden, it should just appear takeable.)

Anyway, I'm going to close this one until I'm convinced the other way makes more sense.
