### ISSUE TITLE
Update links to Timetable and Calendar in footer

### ISSUE THREAD

**Issue by david-yz-liu** [Courseography/courseography#868]
They still point to the 2015-2016 sites, and should point to the 2016-2017 sites instead.

**Comment by AilsaF** [comment]
will work on it

**Comment by david-yz-liu** [comment]
Thanks @AilsaF. Make sure to accept the GitHub invitation to the organization so that I can assign this issue to you.

**Comment by AilsaF** [comment]
Hi I accepted just now :)
