### ISSUE TITLE
Use Data.Char.Ligature to remove ligatures from course descriptions

### ISSUE THREAD

**Issue by david-yz-liu** [Courseography/courseography#869]
Two things to do:

1. Add `ligature` to the list of dependencies
2. Import Data.Char.Ligatures where course data is parsed, and call the [`expand`](https://hackage.haskell.org/package/ligature-0.1.0.0/docs/Data-Char-Ligature.html) function on the course description.

You can check the result by repopulating the database and looking at the course description of CSC207 and making sure the "floating-point" appears properly.

**Comment by RyanDJLee** [comment]
I will attempt to fix this issue.
