### ISSUE TITLE
Reset scrollbar for course info modal when it closes

### ISSUE THREAD

**Issue by david-yz-liu** [Courseography/courseography#870]
Right now, the scroll position is saved when the modal closes and reopens (for a different course). It should be possible to call the jQuery `scrollTop` function when the modal closes to reset the scrollbar.

**Comment by lanaelsanyoura** [comment]
Hi, I would like to work on this.

**Comment by david-yz-liu** [comment]
@lanaelsanyoura okay sure.

1. You need to accept the invitation to the Courseography organization on GitHub so that I can assign to you this issue.
2. Start looking into how the modal is opened in the first place. It will be easier to reset the scrollbar whenever the modal is opened, rather than when it is closed.
