### ISSUE TITLE
Scrolling inside the info modal resizes graph

### ISSUE THREAD

**Issue by Ian-Stewart-Binks** [Courseography/courseography#871]
When a user scrolls inside of the course info modal, the graph resizes.

Steps to reproduce:
1. Go to the [website](https://courseography.cdf.toronto.edu/graph).
2. Open up the computer science graph.
3. Hover over any course and open that course's info modal (click the 'info' tooltip).
4. Scroll down in the info modal, and the graph should resize as well.

Info: Chrome 52.0.2743.116 on Windows

**Comment by david-yz-liu** [comment]
Indeed, @ryanfan mentioned this a long time ago. I thought I made an issue for it, but I guess I never did. Thanks, Ian!

**Comment by lanaelsanyoura** [comment]
Hello, I would like to work on this issue.

**Comment by david-yz-liu** [comment]
@lanaelsanyoura sure! For this one, I think a good first step is to look at where the *scroll event handler* is attached. I think it's currently on the body, which isn't the right choice.
